substitutions:
  devicename:    Ultrasonic Sensor                        # Chose an arbitrary name max 32 characters
  : ultrasonic_sensor                        # chose an arbitrary ID 
  apikey: "/ApGQuwu3PHMk5dgZxNrBIc1fZDGBDfwt3qi8PoTDWg="  # Random Base64 32byte string - for generating > https://esphome.io/components/api.html#configuration-variables
  wifi_ssid: name-of-your-wi-fi                           # Change with the name of your Wi-Fi Access Point
  wifi_password: password-of-your-wifi                    # Change with your Wi-Fi password
  static_ipaddr: 192.168.1.201                            # Change for use a static ip address or to use DHCP, remove this row and manual_ip block
  gateway_ip: 192.168.1.1                                 # Change for use a static ip address or to use DHCP, remove this row and manual_ip block
  subnet_mask: 255.255.255.0                              # Change for use a static ip address or to use DHCP, remove this row and manual_ip block
  dns_ip: 8.8.8.8                                         # Change for use a static ip address or remove this row and manual_ip block
  ap_mode_password: "12345678"                            # Change password for access point mode (fallback)

##############################################################################################################

esphome:
  name: $devicename 
  friendly_name: $devicename_id

esp32:
  board: lolin_s2_mini

# Enable logging
logger:

wifi:
  ssid: $wifi_ssid
  password: $wifi_password
#####################################################################
######            REMOVE THIS BLOCK IF YOU USE DHCP           #######        
#####################################################################
  manual_ip:                                                       ##
    static_ip: $static_ipaddr                                      ##
    gateway:   $gateway_ip                                         ##
    subnet:    $subnet_mask                                        ##
    dns1:      $dns_ip                                             ##
                                                                   ##
#####################################################################

  ap:
    ssid:      $devicename Hotspot
    password:  $ap-mode_password
    
ota:

# Enable Home Assistant API
api:
  encryption:
    key: "6GCVh6zaCGxTTNnAbh6i5l02jxSRsxxG44WL+d1YNYE="

web_server:
  port: 80
  version: 2
  local: true
 
i2c:
  - id: bus_a
    sda: 9
    scl: 11
    scan: true
 
sensor:

  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 10s
    id: bh1750_sensor

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
