esphome:
  name: presence
  friendly_name: presence

esp32:
  board: lolin_s2_mini

# Enable logging
logger:

wifi:
  ssid: io
  password: 316497852Aa
  manual_ip:
    static_ip: 192.168.2.1
    gateway: 192.168.1.1
    subnet: 255.255.252.0

ota:

# Enable Home Assistant API
api:
  encryption:
    key: "O0RBGthZXEVFzyblMGgddy0OwyQezIUKeXXTsyVWEN8="

web_server:
  port: 80
  version: 2
  local: true
 
ld2410:
 
uart:
  tx_pin: GPIO18
  rx_pin: GPIO33
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
 
i2c:
  - id: bus_a
    sda: 9 
    scl: 11
    scan: true
 
sensor:
  - platform: ld2410
    light:
      name: light  
    moving_distance:
      name: Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Moving Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
 
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 10s
    id: bh1750_sensor
 
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status
 
number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold      
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
 
switch:
  - platform: ld2410
    engineering_mode:
      name: Engineering Mode
 
button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params
 
select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level
 
text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"         
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
