esphome:
  name: watertank
  friendly_name: WaterTank

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "uxf2gR/zHQTHdxcQPizXPZcMN1cpPBEoQon+m2QOehE="

ota:
  password: "f21ccb83b26f2f8dbc958a0e3b3b45c2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Watertank Fallback Hotspot"
    password: "9CzXmf2ryQS4"

captive_portal:
    
